export const SET_DEVICE_TYPE = 'set_device_type'
export const SET_DEVICE_MODEL = 'set_device_model'
export const SET_DEVICE_SCREEN_SIZE = 'set_device_screen_size'
export const SET_DEVICE_SERIAL_NO = 'set_device_serial_no'
export const SET_CONTACT_NAME = 'set_contact_name'
export const SET_CONTACT_EMAIL = 'set_contact_email'
export const SUBMIT_TICKET = 'submit_ticket'
